#Shiny launch script
#put into the same folder as the other files
#the path to the data files has to adjusted in the import script before running

Sys.setlocale(category = "LC_ALL", "en_US.UTF-8")
library(caret)
library(data.table)
library(datasets)
library(e1071)
library(forecast)
library(graphics)
library(grDevices)
library(lattice)
library(lubridate)
library(MASS)
library(plyr)
library(stats)
library(stinepack)
library(timeDate)
library(utils)
library(zoo)
library(reshape2)
library(tree)
library(robust)
library(shiny)
source("/Volumes/Nifty/R/Outfittery Inventory Management/Outfittery_IMT/import.R")
source("/Volumes/Nifty/R/Outfittery Inventory Management/Outfittery_IMT/functions.R")
source("/Volumes/Nifty/R/Outfittery Inventory Management/Outfittery_IMT/extra.R")
shiny::runApp("/Volumes/Nifty/R/Outfittery Inventory Management/Outfittery_IMT/")
